[build]
  command = "pnpm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*.js"]
  external_node_modules = ["google-spreadsheet", "google-auth-library"]

