[build]
  command = "pnpm run build"
  publish = "build"
  functions = "netlify/functions"


[functions]
  included_files = ["!static/**"]

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200