cdv2025:
  title: Introduction to Data Visualization
  sections:
    - title: Course Info
      items:
        - title: 'cdv2025: Introduction to Computer Science - Syllabus'
          path: /cdv2025/syllabus
    - title: Fundamentals
      items:
        - title: 'Day 1: Introduction to Computer Science'
          path: /cdv2025/day-1
    - title: Collection and Encoding
      items: []
    - title: Visualization Design
      items: []
    - title: Geographic Visualization
      items: []
    - title: Final Project
      items: []
    - title: Advanced Topics
      items: []
  readings:
    - title: Introduction to Algorithms
      author: Cormen, Leiserson, Rivest, Stein
      pages: 1-20
      url: https://example.com/algorithms-textbook
      path: /cdv2025/day-1
    - title: 'Code: The Hidden Language of Computer Hardware and Software'
      author: Charles Petzold
      pages: 1-15
      url: https://example.com/code-textbook
      path: /cdv2025/day-1
    - title: The Art of Computer Programming, Vol. 1
      author: Donald Knuth
      pages: 10-25
      url: https://example.com/knuth-vol1
      path: /cdv2025/day-1
  assignments:
    - title: Setup Development Environment
      due: '2023-09-12'
      description: Install required software for the course.
      path: /cdv2025/assignments/setup
    - title: First Program
      due: '2023-09-12'
      description: Write your first 'Hello, World' program.
      path: /cdv2025/assignments/hello-world
